#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT=Path(sys.argv[1] if len(sys.argv)>1 else 'dist')

COMMON_EN={
'Международное сотрудничество':'International Development',
'Открыть страницу механизированной уборки ягод':'Open the mechanised berry harvesting page',
'Закрыть меню':'Close menu','Открыть меню':'Open menu','Меню':'Menu',
'Подробнее':'Learn more','← Назад':'← Back',
'Показать другие проекты':'View more projects',
'Выход на рынок Сербии':'Entering the Serbian market',
'Стратегия · локальные партнёры · переговоры':'Strategy · local partners · negotiations',
'Выход технологического стартапа на рынок Сербии':'Technology startup entry into the Serbian market',
'Вывод компании-стартапа из Узбекистана на рынок Сербии. Специализированное ПО для управления BMS-системами зданий. Проведена экспертиза решения, найден локальный партнёр. Проект масштабируется на рынки Балкан.':'Market entry of a technology startup from Uzbekistan into Serbia. The company develops specialised software for building BMS systems. The solution was assessed, a local partner was identified, and the project is now expanding into the Balkan markets.',
'Экспертиза · партнёр · масштабирование':'Assessment · partner · scaling',
'Открытая лаборатория':'Open Laboratory',
'Наука · инфраструктура · удалённый доступ':'Science · infrastructure · remote access',
'Удалённый доступ к исследовательской инфраструктуре':'Remote access to research infrastructure',
'Поиск инвестора для проекта организации удалённого доступа к лабораторному оборудованию исследовательских организаций. Цель проекта — расширить возможности европейских учёных в проведении научных исследований.':'Investor search for a project providing remote access to laboratory equipment at research organisations. The goal is to expand the research capabilities available to European scientists.',
'Инвестиции · наука · инфраструктура · доступ':'Investment · science · infrastructure · access',
'Международная технологическая кооперация':'International Technology Cooperation',
'Международные издательские проекты':'International Publishing Projects',
'Партнёры · локализация · продвижение':'Partners · localisation · promotion',
'Международный книгоиздательский проект':'International publishing project',
'Организация международного издательского проекта по запросу сербского издательства. Международная команда экспертов и авторов готовит исторические книги для сербских читателей.':'Organisation of an international publishing project for a Serbian publisher. An international team of experts and authors is preparing history books for Serbian readers.',
'Эксперты · авторы · локализация · издание':'Experts · authors · localisation · publishing',
'Международный проект по подбору, локализации и трансферу агротехнологий и оборудования с комплексным сопровождением выхода на новые рынки.':'An international project for selecting, localising and transferring agricultural technologies and equipment, with comprehensive support for entering new markets.',
'Стратегия · партнёрство · трансфер технологий':'Strategy · partnership · technology transfer',
'Оптимизация работы ИИ-агентов':'Optimising AI-agent operations',
'ИИ-агенты · аналитика · оптимизация затрат':'AI agents · analytics · cost optimisation',
'ИИ-агенты · контроль · аналитика · экономия':'AI agents · control · analytics · savings',
'Применение решения сербского разработчика ПО в крупной биотехнологической исследовательской компании. Платформа позволяет анализировать и управлять работой ИИ-агентов, а также снижать затраты на использование токенов при их работе.':'Deployment of a Serbian software developer’s solution in a major biotechnology research company. The platform analyses and manages AI-agent operations and helps reduce token-usage costs.',
'Цифровая трансформация банков Казахстана':'Digital transformation of banks in Kazakhstan',
'Вывод цифровой платформы сербского разработчика на рынок Центральной Азии. Внедрение решения на базе process mining и искусственного интеллекта в банках Казахстана для анализа и оптимизации бизнес-процессов.':'Market entry of a Serbian developer’s digital platform into Central Asia. A process-mining and AI solution is being introduced in banks in Kazakhstan to analyse and optimise business processes.',
'банки · Казахстан':'banking · Kazakhstan',
'Шаг ${current+1} из ${steps.length}':'Step ${current+1} of ${steps.length}',
'Пожалуйста, выберите хотя бы один вариант в обязательном вопросе.':'Please select at least one option in the required question.',
'Отправляем…':'Sending…',
'Не удалось отправить заявку. Пожалуйста, попробуйте ещё раз чуть позже.':'We could not submit your enquiry. Please try again a little later.',
'Запись%20на%20консультацию':'Consultation%20booking',
'Создадим новый центр агротехнологий':'Let’s create a new agri-technology centre',
'Место для изображения сельхозугодий в горной местности Центральной Азии':'Agricultural landscape in the mountainous areas of Central Asia',
'Казахстан и Кыргызстан входят в ЕАЭС. Agreement о свободной торговле между Сербией и ЕАЭС действует с 10 июля 2021 года.':'Kazakhstan and Kyrgyzstan are members of the EAEU. The free trade agreement between Serbia and the EAEU has been in force since 10 July 2021.',
'Казахстан и Кыргызстан входят в ЕАЭС. Соглашение о свободной торговле между Сербией и ЕАЭС действует с 10 июля 2021 года.':'Kazakhstan and Kyrgyzstan are members of the EAEU. The free trade agreement between Serbia and the EAEU has been in force since 10 July 2021.',
'— международный консалтинг, трансфер технологий и международные образовательные инициативы.':'— international consulting, technology transfer and international education initiatives.',
'Научно-технологический парк Нови-Сад':'Science and Technology Park Novi Sad',
'Научно-технологический парк Чачак':'Science and Technology Park Čačak',
'Научно-технологический парк Республики Сербской':'Science and Technology Park of Republika Srpska',
'Ассоциация фермеров Казахстана':'Association of Farmers of Kazakhstan',
'Национальный инфраструктурный проект «Туран», Кыргызстан':'National Infrastructure Project “Turan”, Kyrgyz Republic',
'ОБФ «Кыргыз ТехноВумен»':'Kyrgyz TechnoWomen Public Charitable Foundation',
'Торгово-промышленная палата Воеводины':'Chamber of Commerce and Industry of Vojvodina',
'Торгово-промышленная палата Республики Сербской':'Chamber of Commerce and Industry of Republika Srpska',
'Профильные ассоциации, институты развития и деловые объединения':'Specialist associations, development institutions and business organisations',
}

COMMON_CZ={
'Международное сотрудничество':'Mezinárodní rozvoj',
'Открыть страницу механизированной уборки ягод':'Otevřít stránku mechanizované sklizně bobulovin',
'Закрыть меню':'Zavřít menu','Открыть меню':'Otevřít menu','Меню':'Menu',
'Подробнее':'Více informací','← Назад':'← Zpět',
'Показать другие проекты':'Zobrazit další projekty',
'Выход на рынок Сербии':'Vstup na srbský trh',
'Стратегия · локальные партнёры · переговоры':'Strategie · místní partneři · jednání',
'Выход технологического стартапа на рынок Сербии':'Vstup technologického startupu na srbský trh',
'Вывод компании-стартапа из Узбекистана на рынок Сербии. Специализированное ПО для управления BMS-системами зданий. Проведена экспертиза решения, найден локальный партнёр. Проект масштабируется на рынки Балкан.':'Vstup technologického startupu z Uzbekistánu na srbský trh. Společnost vyvíjí specializovaný software pro řízení systémů BMS v budovách. Řešení bylo odborně posouzeno, byl nalezen místní partner a projekt se nyní rozšiřuje na balkánské trhy.',
'Экспертиза · партнёр · масштабирование':'Posouzení · partner · škálování',
'Открытая лаборатория':'Otevřená laboratoř',
'Наука · инфраструктура · удалённый доступ':'Věda · infrastruktura · vzdálený přístup',
'Удалённый доступ к исследовательской инфраструктуре':'Vzdálený přístup k výzkumné infrastruktuře',
'Поиск инвестора для проекта организации удалённого доступа к лабораторному оборудованию исследовательских организаций. Цель проекта — расширить возможности европейских учёных в проведении научных исследований.':'Hledání investora pro projekt vzdáleného přístupu k laboratornímu vybavení výzkumných organizací. Cílem je rozšířit možnosti evropských vědců při provádění výzkumu.',
'Инвестиции · наука · инфраструктура · доступ':'Investice · věda · infrastruktura · přístup',
'Международная технологическая кооперация':'Mezinárodní technologická spolupráce',
'Международные издательские проекты':'Mezinárodní vydavatelské projekty',
'Партнёры · локализация · продвижение':'Partneři · lokalizace · propagace',
'Международный книгоиздательский проект':'Mezinárodní vydavatelský projekt',
'Организация международного издательского проекта по запросу сербского издательства. Международная команда экспертов и авторов готовит исторические книги для сербских читателей.':'Organizace mezinárodního vydavatelského projektu na objednávku srbského nakladatelství. Mezinárodní tým expertů a autorů připravuje historické knihy pro srbské čtenáře.',
'Эксперты · авторы · локализация · издание':'Experti · autoři · lokalizace · vydání',
'Международный проект по подбору, локализации и трансферу агротехнологий и оборудования с комплексным сопровождением выхода на новые рынки.':'Mezinárodní projekt zaměřený na výběr, lokalizaci a transfer zemědělských technologií a zařízení s komplexní podporou vstupu na nové trhy.',
'Стратегия · партнёрство · трансфер технологий':'Strategie · partnerství · transfer technologií',
'Оптимизация работы ИИ-агентов':'Optimalizace provozu AI agentů',
'ИИ-агенты · аналитика · оптимизация затрат':'AI agenti · analytika · optimalizace nákladů',
'ИИ-агенты · контроль · аналитика · экономия':'AI agenti · řízení · analytika · úspory',
'Применение решения сербского разработчика ПО в крупной биотехнологической исследовательской компании. Платформа позволяет анализировать и управлять работой ИИ-агентов, а также снижать затраты на использование токенов при их работе.':'Nasazení řešení srbského softwarového vývojáře ve velké biotechnologické výzkumné společnosti. Platforma umožňuje analyzovat a řídit práci AI agentů a snižovat náklady na spotřebu tokenů.',
'Цифровая трансформация банков Казахстана':'Digitální transformace bank v Kazachstánu',
'Вывод цифровой платформы сербского разработчика на рынок Центральной Азии. Внедрение решения на базе process mining и искусственного интеллекта в банках Казахстана для анализа и оптимизации бизнес-процессов.':'Vstup digitální platformy srbského vývojáře na trh Střední Asie. V bankách v Kazachstánu se zavádí řešení založené na process miningu a umělé inteligenci pro analýzu a optimalizaci podnikových procesů.',
'банки · Казахстан':'bankovnictví · Kazachstán',
'Шаг ${current+1} из ${steps.length}':'Krok ${current+1} z ${steps.length}',
'Пожалуйста, выберите хотя бы один вариант в обязательном вопросе.':'Vyberte prosím alespoň jednu možnost v povinné otázce.',
'Отправляем…':'Odesíláme…',
'Не удалось отправить заявку. Пожалуйста, попробуйте ещё раз чуть позже.':'Poptávku se nepodařilo odeslat. Zkuste to prosím znovu později.',
'Запись%20на%20консультацию':'Rezervace%20konzultace',
'Создадим новый центр агротехнологий':'Vybudujme nové centrum agrotechnologií',
'Место для изображения сельхозугодий в горной местности Центральной Азии':'Zemědělská krajina v horských oblastech Střední Asie',
'Казахстан и Кыргызстан входят в ЕАЭС. Dohoda о свободной торговле между Сербией и ЕАЭС действует с 10 июля 2021 года.':'Kazachstán a Kyrgyzstán jsou členy EAEU. Dohoda o volném obchodu mezi Srbskem a EAEU je účinná od 10. července 2021.',
'Казахстан и Кыргызстан входят в ЕАЭС. Соглашение о свободной торговле между Сербией и ЕАЭС действует с 10 июля 2021 года.':'Kazachstán a Kyrgyzstán jsou členy EAEU. Dohoda o volném obchodu mezi Srbskem a EAEU je účinná od 10. července 2021.',
'— международный консалтинг, трансфер технологий и международные образовательные инициативы.':'— mezinárodní poradenství, transfer technologií a mezinárodní vzdělávací iniciativy.',
'Научно-технологический парк Нови-Сад':'Vědeckotechnologický park Novi Sad',
'Научно-технологический парк Чачак':'Vědeckotechnologický park Čačak',
'Научно-технологический парк Республики Сербской':'Vědeckotechnologický park Republiky srbské',
'Ассоциация фермеров Казахстана':'Asociace farmářů Kazachstánu',
'Национальный инфраструктурный проект «Туран», Кыргызстан':'Národní infrastrukturní projekt „Turan“, Kyrgyzská republika',
'ОБФ «Кыргыз ТехноВумен»':'Veřejná charitativní nadace Kyrgyz TechnoWomen',
'Торгово-промышленная палата Воеводины':'Obchodní a průmyslová komora Vojvodiny',
'Торгово-промышленная палата Республики Сербской':'Obchodní a průmyslová komora Republiky srbské',
'Профильные ассоциации, институты развития и деловые объединения':'Oborové asociace, rozvojové instituce a podnikatelská sdružení',
}

for lang,mapping in [('en',COMMON_EN),('cz',COMMON_CZ)]:
    folder=ROOT/lang
    if not folder.exists():
        continue
    for p in folder.glob('*.html'):
        s=p.read_text(encoding='utf-8')
        for src in sorted(mapping,key=len,reverse=True):
            s=s.replace(src,mapping[src])
        p.write_text(s,encoding='utf-8')

print('Translated current runtime, project-card and late-injected locale strings')
