#!/usr/bin/env python3
from pathlib import Path
import sys

root = Path(sys.argv[1] if len(sys.argv) > 1 else 'dist')
src = root / 'berry-harvesting.html'
if not src.exists():
    raise SystemExit('berry-harvesting.html missing')
source = src.read_text(encoding='utf-8')

COMMON_EN = {
'Механизированная уборка ягод — AGRO TAG':'Mechanized berry harvesting — AGRO TAG',
'AGRO TAG: механизированная бесконтактная уборка ягод, оценка плантации, подбор конфигурации, запуск, обучение и сервис.':'AGRO TAG: contactless mechanized berry harvesting, plantation assessment, configuration selection, commissioning, training and service.',
'← Назад к AGRO TAG':'← Back to AGRO TAG',
'Технология':'Technology','Преимущества':'Benefits','Для каких хозяйств':'Who it is for','Модели':'Models','Подготовка плантации':'Plantation readiness','Запросить консультацию':'Request consultation',
'Механизированная уборка ягод для свежего рынка':'Mechanized berry harvesting for the fresh market',
'Бесконтактная технология сбора спелой ягоды управляемыми импульсами воздуха. Снижение зависимости от сезонных рабочих — при бережном воздействии на растение и урожай.':'Contactless harvesting technology uses controlled air pulses to detach ripe berries, reducing dependence on seasonal labour while treating plants and fruit gently.',
'Подобрать решение для хозяйства':'Find the right solution','Как работает технология':'How the technology works',
'Проблема':'The challenge','Когда урожай есть, а рабочих не хватает':'When the crop is ready but labour is scarce',
'Ручная уборка ягод требует большого количества сезонного персонала именно в короткий период, когда урожай необходимо собрать быстро и с минимальными потерями.':'Manual berry harvesting requires large seasonal crews during a short window when the crop must be collected quickly and with minimal losses.',
'Снижение зависимости от сезонных рабочих':'Lower dependence on seasonal labour','Более предсказуемые сроки уборки':'More predictable harvest timing','Возможность обслуживать большие площади':'Ability to cover larger areas','Снижение операционных рисков':'Lower operational risk','Ягодная плантация':'Berry plantation',
'Экономика уборки':'Harvest economics','Производительность, которая меняет экономику':'Productivity that changes harvest economics','Ориентир в зависимости от модели, культуры и условий.':'Indicative output depending on model, crop and conditions.','Для голубичных плантаций в подходящих условиях.':'For blueberry plantations under suitable conditions.','Эквивалент сборщиков в сравнении со средней производительностью ручного труда.':'Equivalent number of pickers compared with average manual productivity.',
'Сила природы — под контролем':'The force of nature — under control','Регулируемые импульсы воздуха отделяют зрелую ягоду без непосредственного жёсткого механического контакта с растением.':'Controlled air pulses detach ripe berries without direct hard mechanical contact with the plant.','Импульсные воздушные потоки':'Pulsed air flows','Управляемая скорость и частота воздушного воздействия.':'Controlled air velocity and pulse frequency.','Мягкая система приёма':'Soft fruit receiving system','Эластичные элементы поглощают энергию падающей ягоды и снижают риск повреждения.':'Elastic air-filled elements absorb the energy of falling berries and reduce the risk of damage.','Дисковая система улавливания':'Disc catching system','Минимизирует пространство вокруг ствола и помогает уменьшать потери ягоды.':'Minimizes gaps around the stem and helps reduce fruit losses.','Направляющие элементы':'Guiding elements','Направляют ветви и помогают адаптировать процесс к различным культурам.':'Guide branches and help adapt the process to different crops.',
'Бережный принцип':'Gentle harvesting principle','Механизированная уборка без жёсткого контакта':'Mechanized harvesting without hard contact','Созревшая ягода удерживается растением слабее, чем незрелая. Правильно настроенное воздушное воздействие использует это различие.':'Ripe fruit is held less firmly by the plant than unripe fruit. Properly tuned air action uses this difference.','Спелая ягода → отделяется':'Ripe berry → detaches','Настройки подбираются под культуру, зрелость и состояние насаждений.':'Settings are adapted to crop, ripeness and plantation condition.','Незрелая ягода → остаётся':'Unripe berry → remains','Цель — сохранить незрелые плоды на растении и снизить нежелательное воздействие.':'The objective is to keep unripe fruit on the plant and minimize unwanted impact.',
'Культуры':'Crops','Одна технология — несколько ягодных культур':'One technology — multiple berry crops','Основное современное применение — механизированная уборка голубики для свежего рынка. Технология также применяется для других ягодных культур.':'The main modern application is mechanized blueberry harvesting for the fresh market. The technology is also used with other berry crops.','Голубика':'Blueberry','Малина':'Raspberry','Ежевика':'Blackberry','Чёрная смородина':'Blackcurrant','Жимолость':'Haskap',
'Механизированная уборка начинается с плантации':'Mechanized harvesting starts with the plantation','Результат зависит не только от оборудования. Сорт, форма растения, схема посадки и состояние плантации напрямую влияют на эффективность уборки.':'Results depend on more than the machine. Variety, plant architecture, row layout and plantation condition directly influence harvesting efficiency.','СОРТ':'VARIETY','Созревание и свойства ягоды':'Ripening and fruit properties','Равномерность созревания, размер, урожайность, вертикальная структура и плотность плода.':'Ripening uniformity, berry size, yield, vertical plant structure and fruit firmness.','ФОРМИРОВАНИЕ':'PLANT TRAINING','Архитектура куста':'Plant architecture','Узкое основание, высота нижних ветвей, плодоносящие побеги и объём зелёной массы.':'Narrow base, lower branch height, fruiting shoots and total canopy volume.','ПОСАДКА':'LAYOUT','Геометрия и условия':'Geometry and conditions','Междурядья, разворот техники, шпалеры, тоннели, температура, влажность и время уборки.':'Row spacing, turning area, trellises, tunnels, temperature, humidity and harvest timing.',
'Предварительная оценка':'Preliminary assessment','Проверьте, подходит ли ваша плантация':'Check whether your plantation is suitable','пространство для разворота техники':'turning space for machinery','ориентир по высоте конструкций внутри ряда':'indicative maximum structure height within the row','ориентир по высоте тоннелей':'indicative tunnel height','пример междурядья в приведённой схеме':'example row spacing in the reference layout','Точные параметры определяются после оценки конкретной плантации и выбранной конфигурации оборудования.':'Exact parameters are determined after assessment of the specific plantation and selected equipment configuration.',
'Конфигурации':'Configurations','Конфигурация под масштаб хозяйства':'A configuration for the scale of your farm','Прицепная версия':'Towed version','Привод от ВОМ. Для хозяйств с подходящим трактором.':'PTO driven. For farms with a suitable tractor.','Автономная прицепная версия':'Independent towed version','Собственный дизельный двигатель. Больше независимости от мощности тягача.':'Own diesel engine. Greater independence from tractor power.','Самоходная версия':'Self-propelled version','Для крупных хозяйств и интенсивной эксплуатации.':'For larger farms and intensive operation.','Посмотреть характеристики':'View specifications','Финальная комплектация и совместимость определяются после консультации.':'Final specification and compatibility are confirmed during consultation.',
'Переход к механизации':'Transition to mechanization','Механизация — это процесс, а не покупка одной машины':'Mechanization is a process, not simply buying one machine','Существующая плантация':'Existing plantation','Год 1 · адаптация':'Year 1 · adaptation','Год 2 · рост доли':'Year 2 · increasing share','Год 3 · масштабирование':'Year 3 · scaling','Для неподготовленных плантаций переход может идти поэтапно: ориентировочно 10–15% → около 40% → 60%+ механизированной уборки.':'For plantations not originally designed for mechanization, the transition can be gradual: approximately 10–15% → around 40% → 60%+ mechanized harvesting.','Новая плантация':'New plantation','Проектирование сразу под механизацию':'Designed for mechanization from the start','При проектировании посадок под технологию возможно существенно быстрее наращивать долю механизированной уборки.':'Designing new plantings around the technology can allow a much faster increase in the mechanized share.',
'Не просто оборудование. Система внедрения.':'More than equipment. An implementation system.','AGRO TAG сопровождает внедрение технологии от первичной оценки хозяйства до запуска оборудования и последующей сервисной поддержки.':'AGRO TAG supports implementation from initial farm assessment through commissioning and ongoing service support.','Анализ хозяйства':'Farm analysis','Подбор технологии':'Technology selection','Оценка плантации':'Plantation assessment','Поставка':'Delivery','Запуск':'Commissioning','Обучение':'Training','Сервис':'Service','Запасные части':'Spare parts',
'Когда стоит рассматривать механизированную уборку':'When mechanized harvesting makes sense','Растущие затраты на сезонных рабочих':'Rising seasonal labour costs','Нехватка персонала':'Labour shortages','Увеличение площади плантаций':'Expanding plantation area','Необходимость быстрее завершать уборку':'Need to complete harvest faster','Ориентация на свежий рынок':'Fresh-market focus','Планирование новых посадок':'Planning new plantings','Возможность адаптации насаждений':'Ability to adapt existing plantings','Потребность в предсказуемой производительности':'Need for predictable productivity',
'Международный опыт':'International experience','Технология работает на международных рынках':'Technology operating in international markets','машин в международной эксплуатации':'machines operating internationally','разработки и полевого опыта':'of development and field experience','машин в США за первые два года развития рынка':'machines in the US during the first two years of market development',
'Новые проекты':'New projects','Планируете новую ягодную плантацию?':'Planning a new berry plantation?','Лучший момент для подготовки к механизированной уборке — ещё до посадки. Мы можем обсудить геометрию рядов, технологический сценарий и требования к будущей механизации.':'The best time to prepare for mechanized harvesting is before planting. We can discuss row geometry, the technology scenario and future mechanization requirements.','Обсудить проект плантации':'Discuss a plantation project','Новая ягодная плантация':'New berry plantation',
'Консультация':'Consultation','Подходит ли механизированная уборка вашему хозяйству?':'Is mechanized harvesting suitable for your farm?','Расскажите о культуре, площади и существующей схеме посадки. AGRO TAG поможет предварительно оценить возможность механизации и подобрать конфигурацию оборудования.':'Tell us about your crop, area and current planting layout. AGRO TAG will help make a preliminary assessment of mechanization potential and select an appropriate equipment configuration.','Имя':'Name','Компания':'Company','Страна':'Country','Культура':'Crop','Площадь, га':'Area, ha','Тип проекта':'Project type','Существующая плантация':'Existing plantation','Расширение существующей':'Expansion of existing plantation','Телефон':'Phone','Комментарий':'Comment','Другое':'Other','Смородина':'Currant','Оценить возможность механизации':'Assess mechanization potential'
}

COMMON_CZ = {
'Механизированная уборка ягод — AGRO TAG':'Mechanizovaná sklizeň bobulovin — AGRO TAG',
'AGRO TAG: механизированная бесконтактная уборка ягод, оценка плантации, подбор конфигурации, запуск, обучение и сервис.':'AGRO TAG: bezkontaktní mechanizovaná sklizeň bobulovin, posouzení plantáže, výběr konfigurace, uvedení do provozu, školení a servis.',
'← Назад к AGRO TAG':'← Zpět na AGRO TAG','Технология':'Technologie','Преимущества':'Výhody','Для каких хозяйств':'Pro jaké podniky','Модели':'Modely','Подготовка плантации':'Příprava plantáže','Запросить консультацию':'Požádat o konzultaci',
'Механизированная уборка ягод для свежего рынка':'Mechanizovaná sklizeň bobulovin pro čerstvý trh','Бесконтактная технология сбора спелой ягоды управляемыми импульсами воздуха. Снижение зависимости от сезонных рабочих — при бережном воздействии на растение и урожай.':'Bezkontaktní technologie sklizně zralých bobulí pomocí řízených pulzů vzduchu. Snižuje závislost na sezónních pracovnících a zároveň šetrně působí na rostliny i plody.','Подобрать решение для хозяйства':'Vybrat řešení pro podnik','Как работает технология':'Jak technologie funguje',
'Проблема':'Výzva','Когда урожай есть, а рабочих не хватает':'Když je úroda připravena, ale chybějí pracovníci','Ручная уборка ягод требует большого количества сезонного персонала именно в короткий период, когда урожай необходимо собрать быстро и с минимальными потерями.':'Ruční sklizeň bobulovin vyžaduje mnoho sezónních pracovníků právě v krátkém období, kdy je třeba úrodu sklidit rychle a s minimálními ztrátami.','Снижение зависимости от сезонных рабочих':'Menší závislost na sezónní pracovní síle','Более предсказуемые сроки уборки':'Předvídatelnější termíny sklizně','Возможность обслуживать большие площади':'Možnost obsluhovat větší plochy','Снижение операционных рисков':'Snížení provozních rizik','Ягодная плантация':'Plantáž bobulovin',
'Экономика уборки':'Ekonomika sklizně','Производительность, которая меняет экономику':'Výkon, který mění ekonomiku sklizně','Ориентир в зависимости от модели, культуры и условий.':'Orientační výkon podle modelu, plodiny a podmínek.','Для голубичных плантаций в подходящих условиях.':'Pro borůvkové plantáže za vhodných podmínek.','Эквивалент сборщиков в сравнении со средней производительностью ручного труда.':'Ekvivalent počtu sběračů ve srovnání s průměrnou produktivitou ruční práce.',
'Сила природы — под контролем':'Síla přírody pod kontrolou','Регулируемые импульсы воздуха отделяют зрелую ягоду без непосредственного жёсткого механического контакта с растением.':'Řízené pulzy vzduchu oddělují zralé bobule bez přímého tvrdého mechanického kontaktu s rostlinou.','Импульсные воздушные потоки':'Pulzní proudění vzduchu','Управляемая скорость и частота воздушного воздействия.':'Řízená rychlost a frekvence působení vzduchu.','Мягкая система приёма':'Šetrný systém zachycení plodů','Эластичные элементы поглощают энергию падающей ягоды и снижают риск повреждения.':'Elastické prvky absorbují energii padajících bobulí a snižují riziko poškození.','Дисковая система улавливания':'Diskový záchytný systém','Минимизирует пространство вокруг ствола и помогает уменьшать потери ягоды.':'Minimalizuje mezery kolem kmene a pomáhá omezovat ztráty plodů.','Направляющие элементы':'Vodicí prvky','Направляют ветви и помогают адаптировать процесс к различным культурам.':'Vedou větve a pomáhají přizpůsobit proces různým plodinám.',
'Бережный принцип':'Šetrný princip','Механизированная уборка без жёсткого контакта':'Mechanizovaná sklizeň bez tvrdého kontaktu','Созревшая ягода удерживается растением слабее, чем незрелая. Правильно настроенное воздушное воздействие использует это различие.':'Zralý plod drží na rostlině slaběji než nezralý. Správně nastavené působení vzduchu tento rozdíl využívá.','Спелая ягода → отделяется':'Zralá bobule → oddělí se','Настройки подбираются под культуру, зрелость и состояние насаждений.':'Nastavení se přizpůsobuje plodině, zralosti a stavu porostu.','Незрелая ягода → остаётся':'Nezralá bobule → zůstává','Цель — сохранить незрелые плоды на растении и снизить нежелательное воздействие.':'Cílem je ponechat nezralé plody na rostlině a minimalizovat nežádoucí působení.',
'Культуры':'Plodiny','Одна технология — несколько ягодных культур':'Jedna technologie — více druhů bobulovin','Основное современное применение — механизированная уборка голубики для свежего рынка. Технология также применяется для других ягодных культур.':'Hlavním současným využitím je mechanizovaná sklizeň borůvek pro čerstvý trh. Technologie se používá také u dalších bobulovin.','Голубика':'Borůvka','Малина':'Malina','Ежевика':'Ostružina','Чёрная смородина':'Černý rybíz','Жимолость':'Zimolez',
'Механизированная уборка начинается с плантации':'Mechanizovaná sklizeň začíná u plantáže','Результат зависит не только от оборудования. Сорт, форма растения, схема посадки и состояние плантации напрямую влияют на эффективность уборки.':'Výsledek nezávisí jen na stroji. Odrůda, architektura rostlin, schéma výsadby a stav plantáže přímo ovlivňují efektivitu sklizně.','СОРТ':'ODRŮDA','Созревание и свойства ягоды':'Zrání a vlastnosti plodu','Равномерность созревания, размер, урожайность, вертикальная структура и плотность плода.':'Rovnoměrnost zrání, velikost, výnos, vertikální struktura a pevnost plodu.','ФОРМИРОВАНИЕ':'TVAROVÁNÍ','Архитектура куста':'Architektura keře','Узкое основание, высота нижних ветвей, плодоносящие побеги и объём зелёной массы.':'Úzká báze, výška spodních větví, plodonosné výhony a objem zelené hmoty.','ПОСАДКА':'VÝSADBA','Геометрия и условия':'Geometrie a podmínky','Междурядья, разворот техники, шпалеры, тоннели, температура, влажность и время уборки.':'Rozteč řádků, prostor pro otáčení techniky, opěrné konstrukce, tunely, teplota, vlhkost a termín sklizně.',
'Предварительная оценка':'Předběžné posouzení','Проверьте, подходит ли ваша плантация':'Zjistěte, zda je vaše plantáž vhodná','пространство для разворота техники':'prostor pro otáčení techniky','ориентир по высоте конструкций внутри ряда':'orientační výška konstrukcí v řádku','ориентир по высоте тоннелей':'orientační výška tunelů','пример междурядья в приведённой схеме':'příklad rozteče řádků v uvedeném schématu','Точные параметры определяются после оценки конкретной плантации и выбранной конфигурации оборудования.':'Přesné parametry se stanoví po posouzení konkrétní plantáže a zvolené konfigurace zařízení.',
'Конфигурации':'Konfigurace','Конфигурация под масштаб хозяйства':'Konfigurace podle velikosti podniku','Прицепная версия':'Tažená verze','Привод от ВОМ. Для хозяйств с подходящим трактором.':'Pohon z vývodového hřídele. Pro podniky s vhodným traktorem.','Автономная прицепная версия':'Nezávislá tažená verze','Собственный дизельный двигатель. Больше независимости от мощности тягача.':'Vlastní dieselový motor. Vyšší nezávislost na výkonu traktoru.','Самоходная версия':'Samojízdná verze','Для крупных хозяйств и интенсивной эксплуатации.':'Pro velké podniky a intenzivní provoz.','Посмотреть характеристики':'Zobrazit parametry','Финальная комплектация и совместимость определяются после консультации.':'Konečná specifikace a kompatibilita se stanoví při konzultaci.',
'Переход к механизации':'Přechod k mechanizaci','Механизация — это процесс, а не покупка одной машины':'Mechanizace je proces, ne pouze nákup jednoho stroje','Существующая плантация':'Stávající plantáž','Год 1 · адаптация':'Rok 1 · adaptace','Год 2 · рост доли':'Rok 2 · zvýšení podílu','Год 3 · масштабирование':'Rok 3 · rozšíření','Для неподготовленных плантаций переход может идти поэтапно: ориентировочно 10–15% → около 40% → 60%+ механизированной уборки.':'U plantáží, které nebyly původně připraveny na mechanizaci, může přechod probíhat postupně: přibližně 10–15 % → kolem 40 % → 60 % a více mechanizované sklizně.','Новая плантация':'Nová plantáž','Проектирование сразу под механизацию':'Projektování od začátku pro mechanizaci','При проектировании посадок под технологию возможно существенно быстрее наращивать долю механизированной уборки.':'Při návrhu nové výsadby s ohledem na technologii lze podíl mechanizované sklizně zvyšovat výrazně rychleji.',
'Не просто оборудование. Система внедрения.':'Nejen zařízení. Systém zavedení.','AGRO TAG сопровождает внедрение технологии от первичной оценки хозяйства до запуска оборудования и последующей сервисной поддержки.':'AGRO TAG podporuje zavedení technologie od prvotního posouzení podniku až po uvedení zařízení do provozu a následnou servisní podporu.','Анализ хозяйства':'Analýza podniku','Подбор технологии':'Výběr technologie','Оценка плантации':'Posouzení plantáže','Поставка':'Dodávka','Запуск':'Uvedení do provozu','Обучение':'Školení','Сервис':'Servis','Запасные части':'Náhradní díly',
'Когда стоит рассматривать механизированную уборку':'Kdy stojí za to uvažovat o mechanizované sklizni','Растущие затраты на сезонных рабочих':'Rostoucí náklady na sezónní pracovníky','Нехватка персонала':'Nedostatek pracovníků','Увеличение площади плантаций':'Rozšiřování plantáží','Необходимость быстрее завершать уборку':'Potřeba rychleji dokončit sklizeň','Ориентация на свежий рынок':'Zaměření na čerstvý trh','Планирование новых посадок':'Plánování nové výsadby','Возможность адаптации насаждений':'Možnost přizpůsobit stávající porost','Потребность в предсказуемой производительности':'Potřeba předvídatelné produktivity',
'Международный опыт':'Mezinárodní zkušenosti','Технология работает на международных рынках':'Technologie funguje na mezinárodních trzích','машин в международной эксплуатации':'strojů v mezinárodním provozu','разработки и полевого опыта':'vývoje a zkušeností z provozu','машин в США за первые два года развития рынка':'strojů v USA během prvních dvou let rozvoje trhu',
'Новые проекты':'Nové projekty','Планируете новую ягодную плантацию?':'Plánujete novou plantáž bobulovin?','Лучший момент для подготовки к механизированной уборке — ещё до посадки. Мы можем обсудить геометрию рядов, технологический сценарий и требования к будущей механизации.':'Nejlepší čas na přípravu mechanizované sklizně je ještě před výsadbou. Můžeme projednat geometrii řádků, technologický scénář a požadavky na budoucí mechanizaci.','Обсудить проект плантации':'Projednat projekt plantáže','Новая ягодная плантация':'Nová plantáž bobulovin',
'Консультация':'Konzultace','Подходит ли механизированная уборка вашему хозяйству?':'Je mechanizovaná sklizeň vhodná pro váš podnik?','Расскажите о культуре, площади и существующей схеме посадки. AGRO TAG поможет предварительно оценить возможность механизации и подобрать конфигурацию оборудования.':'Sdělte nám plodinu, plochu a současné schéma výsadby. AGRO TAG pomůže předběžně posoudit možnost mechanizace a vybrat vhodnou konfiguraci zařízení.','Имя':'Jméno','Компания':'Společnost','Страна':'Země','Культура':'Plodina','Площадь, га':'Plocha, ha','Тип проекта':'Typ projektu','Существующая плантация':'Stávající plantáž','Расширение существующей':'Rozšíření stávající plantáže','Телефон':'Telefon','Комментарий':'Komentář','Другое':'Jiné','Смородина':'Rybíz','Оценить возможность механизации':'Posoudit možnost mechanizace'
}

def make(lang, mapping):
    s = source
    for old in sorted(mapping, key=len, reverse=True):
        s = s.replace(old, mapping[old])
    s = s.replace('<html lang="ru">', f'<html lang="{lang}">')
    s = s.replace('src="assets/', 'src="../assets/')
    if lang == 'en':
        s = s.replace('<a href="en/berry-harvesting.html">EN</a><a href="cz/berry-harvesting.html">CZ</a><a class="active" href="berry-harvesting.html">RU</a>', '<a class="active" href="berry-harvesting.html">EN</a><a href="../cz/berry-harvesting.html">CZ</a><a href="../berry-harvesting.html">RU</a>')
    else:
        s = s.replace('<a href="en/berry-harvesting.html">EN</a><a href="cz/berry-harvesting.html">CZ</a><a class="active" href="berry-harvesting.html">RU</a>', '<a href="../en/berry-harvesting.html">EN</a><a class="active" href="berry-harvesting.html">CZ</a><a href="../berry-harvesting.html">RU</a>')
    out = root / lang / 'berry-harvesting.html'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(s, encoding='utf-8')

make('en', COMMON_EN)
make('cz', COMMON_CZ)
print('Generated berry harvesting EN/CZ pages')
