#!/usr/bin/env python3
from pathlib import Path
import re
import sys

ROOT=Path(sys.argv[1] if len(sys.argv)>1 else 'dist')
src=ROOT/'berry-harvesting.html'
if not src.exists():
    raise SystemExit('Missing final berry-harvesting.html')

EN={
'Механизированная уборка ягод — AGRO TAG':'Mechanised Berry Harvesting — AGRO TAG',
'AGRO TAG: механизированная бесконтактная уборка ягод, оценка плантации, подбор конфигурации, запуск, обучение и сервис.':'AGRO TAG: contactless mechanised berry harvesting, plantation assessment, configuration selection, commissioning, training and service.',
'← Назад к AGRO TAG':'← Back to AGRO TAG',
'Эффективность':'Efficiency','Технология':'Technology','Бережный принцип':'Gentle harvesting','Модели':'Models','Подготовка плантации':'Plantation preparation','Система внедрения':'Implementation system','Консультация':'Consultation',
'Преимущества':'Benefits','Для каких хозяйств':'Who it is for','Запросить консультацию':'Request a consultation',
'Инновационная технология':'Innovative technology','Воздушно-импульсная уборка':'Air-pulse harvesting',
'Механизированная уборка ягод для свежего рынка':'Mechanised berry harvesting for the fresh market',
'Бесконтактная технология сбора спелой ягоды и фруктов управляемыми импульсами воздуха. Снижение зависимости от сезонных рабочих — при бережном воздействии на растение и урожай.':'A contactless technology for harvesting ripe berries and fruit with controlled air pulses. It reduces dependence on seasonal labour while treating plants and crops gently.',
'Бесконтактная технология сбора спелой ягоды управляемыми импульсами воздуха. Снижение зависимости от сезонных рабочих — при бережном воздействии на растение и урожай.':'A contactless technology for harvesting ripe berries with controlled air pulses. It reduces dependence on seasonal labour while treating plants and crops gently.',
'Подобрать решение для хозяйства':'Find a solution for your farm','Как работает технология':'How the technology works',
'Типичные проблемы ручной уборки':'Typical challenges of manual harvesting','Когда ручной сбор становится ограничением':'When manual harvesting becomes a constraint','Ручной сбор ограничивает скорость, масштаб хозяйства и стабильность качества ягоды.':'Manual harvesting limits speed, farm scale and consistency of berry quality.',
'Операционные ограничения':'Operational constraints','Люди · сроки · масштаб':'Labour · timing · scale','Риски для качества урожая':'Crop-quality risks','Ягода · зрелость · хранение':'Fruit · ripeness · storage',
'Дефицит сезонных рабочих':'Seasonal labour shortages','Рост стоимости ручного труда':'Rising manual-labour costs','Непредсказуемые сроки уборки':'Unpredictable harvest timing','Ограничение масштаба хозяйства':'Limits on farm scale','Повреждение ягод':'Berry damage','Потеря защитного воскового налёта':'Loss of the protective wax bloom','Неоднородная зрелость партии':'Uneven batch ripeness','Перегрев и задержка охлаждения':'Overheating and delayed cooling',
'Проблема':'Challenge','Когда урожай есть, а рабочих не хватает':'When the crop is ready but labour is not available','Ручная уборка ягод требует большого количества сезонного персонала именно в короткий период, когда урожай необходимо собрать быстро и с минимальными потерями.':'Manual berry harvesting requires a large seasonal workforce during a short window when the crop must be collected quickly and with minimal losses.',
'Снижение зависимости от сезонных рабочих':'Lower dependence on seasonal labour','Более предсказуемые сроки уборки':'More predictable harvest timing','Возможность обслуживать большие площади':'Ability to cover larger areas','Снижение операционных рисков':'Lower operational risk','Ягодная плантация':'Berry plantation',
'Мы создаем новую экономику уборки':'Creating new harvesting economics','Мы создаём новую экономику уборки':'Creating new harvesting economics','Производительность, которая меняет экономику':'Productivity that changes the economics','Экономика уборки':'Harvest economics',
'до 500+ кг/час':'up to 500+ kg/hour','500+ кг/час':'500+ kg/hour','Ориентир в зависимости от модели, культуры и условий.':'Indicative performance depending on model, crop and conditions.','до 4 га/день':'up to 4 ha/day','Для ягодных плантаций в подходящих условиях.':'For berry plantations under suitable conditions.','Для голубичных плантаций в подходящих условиях.':'For blueberry plantations under suitable conditions.','Эквивалент сборщиков в сравнении со средней производительностью ручного труда.':'Equivalent number of pickers compared with average manual-harvesting productivity.',
'Сила природы — под контролем':'The force of nature — under control','Регулируемые импульсы воздуха отделяют зрелую ягоду без непосредственного жёсткого механического контакта с растением.':'Controlled air pulses detach ripe berries without harsh direct mechanical contact with the plant.','Импульсные воздушные потоки':'Pulsed air streams','Управляемая скорость и частота воздушного воздействия.':'Controlled air speed and pulse frequency.','Мягкая система приёма':'Gentle collection system','Эластичные элементы поглощают энергию падающей ягоды и снижают риск повреждения.':'Elastic elements absorb the energy of falling berries and reduce the risk of damage.','Дисковая система улавливания':'Disc catching system','Минимизирует пространство вокруг ствола и помогает уменьшать потери ягоды.':'Minimises gaps around the trunk and helps reduce fruit losses.','Направляющие элементы':'Guiding elements','Направляют ветви и помогают адаптировать процесс к различным культурам.':'Guide branches and help adapt the process to different crops.',
'Механизированная уборка без жёсткого контакта':'Mechanised harvesting without harsh contact','Созревшая ягода удерживается растением слабее, чем незрелая. Правильно настроенное воздушное воздействие использует это различие.':'Ripe berries are held less firmly by the plant than unripe fruit. Properly calibrated air pulses make use of this difference.','Спелая ягода → отделяется':'Ripe berry → detaches','Настройки подбираются под культуру, зрелость и состояние насаждений.':'Settings are matched to the crop, ripeness and condition of the plantation.','Незрелая ягода → остаётся':'Unripe berry → remains','Цель — сохранить незрелые плоды на растении и снизить нежелательное воздействие.':'The goal is to keep unripe fruit on the plant and minimise unwanted impact.',
'Культуры':'Crops','Одна технология — несколько ягодных культур':'One technology — several berry crops','Основное современное применение — механизированная уборка голубики для свежего рынка. Технология также применяется для других ягодных культур.':'The main modern application is mechanised blueberry harvesting for the fresh market. The technology is also used with other berry crops.','Голубика':'Blueberry','Малина':'Raspberry','Ежевика':'Blackberry','Чёрная смородина':'Blackcurrant','Смородина':'Currant','Жимолость':'Haskap',
'Механизированная уборка начинается с плантации':'Mechanised harvesting starts with the plantation','Результат зависит не только от оборудования. Сорт, форма растения, схема посадки и состояние плантации напрямую влияют на эффективность уборки.':'Results depend on more than the machine. Variety, plant shape, planting geometry and plantation condition directly affect harvesting efficiency.','СОРТ':'VARIETY','Созревание и свойства ягоды':'Ripening and berry characteristics','Равномерность созревания, размер, урожайность, вертикальная структура и плотность плода.':'Ripening uniformity, size, yield, vertical structure and fruit firmness.','ФОРМИРОВАНИЕ':'TRAINING','Архитектура куста':'Plant architecture','Узкое основание, высота нижних ветвей, плодоносящие побеги и объём зелёной массы.':'Narrow base, height of lower branches, fruiting shoots and canopy volume.','ПОСАДКА':'PLANTING','Геометрия и условия':'Geometry and conditions','Междурядья, разворот техники, шпалеры, тоннели, температура, влажность и время уборки.':'Row spacing, turning space, trellises, tunnels, temperature, humidity and harvest timing.',
'Предварительная оценка':'Preliminary assessment','Проверьте, подходит ли ваша плантация':'Check whether your plantation is suitable','пространство для разворота техники':'turning space for machinery','ориентир по высоте конструкций внутри ряда':'indicative height of structures within the row','ориентир по высоте тоннелей':'indicative tunnel height','пример междурядья в приведённой схеме':'example row spacing in the illustrated layout','Точные параметры определяются после оценки конкретной плантации и выбранной конфигурации оборудования.':'Exact parameters are determined after assessing the specific plantation and equipment configuration.',
'Конфигурации':'Configurations','Конфигурация под масштаб хозяйства':'A configuration matched to farm scale','Прицепная версия':'Trailed version','Привод от ВОМ. Для хозяйств с подходящим трактором.':'PTO-driven. For farms with a suitable tractor.','Автономная прицепная версия':'Self-powered trailed version','Собственный дизельный двигатель. Больше независимости от мощности тягача.':'Own diesel engine for greater independence from tractor power.','Самоходная версия':'Self-propelled version','Для крупных хозяйств и интенсивной эксплуатации.':'For larger farms and intensive operation.','Посмотреть характеристики':'View specifications','Финальная комплектация и совместимость определяются после консультации.':'Final configuration and compatibility are confirmed after consultation.',
'Переход к механизации':'Transition to mechanisation','Механизация — это процесс, а не покупка одной машины':'Mechanisation is a process, not simply a machine purchase','Существующая плантация':'Existing plantation','Год 1 · адаптация':'Year 1 · adaptation','Год 2 · рост доли':'Year 2 · increasing share','Год 3 · масштабирование':'Year 3 · scaling','Для неподготовленных плантаций переход может идти поэтапно: ориентировочно 10–15% → около 40% → 60%+ механизированной уборки.':'For unprepared plantations, the transition may be gradual: approximately 10–15% → around 40% → 60%+ mechanised harvesting.','Новая плантация':'New plantation','Проектирование сразу под механизацию':'Designed for mechanisation from the outset','При проектировании посадок под технологию возможно существенно быстрее наращивать долю механизированной уборки.':'Designing new plantings around the technology can significantly accelerate the transition to mechanised harvesting.',
'Не просто оборудование. Система внедрения.':'More than equipment. An implementation system.','Поставщик сопровождает внедрение технологии от первичной оценки хозяйства до запуска оборудования и последующей сервисной поддержки.':'The supplier supports implementation from the initial farm assessment through equipment commissioning and ongoing service.','AGRO TAG сопровождает внедрение технологии от первичной оценки хозяйства до запуска оборудования и последующей сервисной поддержки.':'AGRO TAG supports implementation from the initial farm assessment through equipment commissioning and ongoing service.','Анализ хозяйства':'Farm analysis','Подбор технологии':'Technology selection','Оценка участка':'Site assessment','Оценка плантации':'Plantation assessment','Поставка':'Delivery','Запуск':'Commissioning','Обучение':'Training','Сервис':'Service','Запасные части':'Spare parts',
'Когда стоит рассматривать механизированную уборку':'When to consider mechanised harvesting','Растущие затраты на сезонных рабочих':'Rising seasonal-labour costs','Нехватка персонала':'Labour shortages','Увеличение площади плантаций':'Expanding plantation area','Необходимость быстрее завершать уборку':'Need to complete harvest faster','Ориентация на свежий рынок':'Focus on the fresh market','Планирование новых посадок':'Planning new plantings','Возможность адаптации насаждений':'Ability to adapt plantations','Потребность в предсказуемой производительности':'Need for predictable productivity',
'Международный опыт':'International experience','Технология работает на международных рынках':'Technology proven in international markets','машин в международной эксплуатации':'machines in international operation','20+ лет':'20+ years','разработки и полевого опыта':'of development and field experience','машин в США за первые два года развития рынка':'machines in the US during the first two years of market development',
'Новые проекты':'New projects','Планируете новую ягодную плантацию?':'Planning a new berry plantation?','Лучший момент для подготовки к механизированной уборке — ещё до посадки. Мы можем обсудить геометрию рядов, технологический сценарий и требования к будущей механизации.':'The best time to prepare for mechanised harvesting is before planting. We can discuss row geometry, the operating concept and requirements for future mechanisation.','Обсудить проект плантации':'Discuss a plantation project',
'Подходит ли механизированная уборка вашему хозяйству?':'Is mechanised harvesting suitable for your farm?','Расскажите о культуре, площади и существующей схеме посадки. AGRO TAG поможет предварительно оценить возможность механизации и подобрать конфигурацию оборудования.':'Tell us about your crop, area and existing planting layout. AGRO TAG will help assess the potential for mechanisation and select an equipment configuration.','Имя':'Name','Компания':'Company','Страна':'Country','Культура':'Crop','Площадь, га':'Area, ha','Тип проекта':'Project type','Телефон':'Phone','Комментарий':'Comment','Расширение существующей':'Expansion of an existing plantation','Оценить возможность механизации':'Assess mechanisation potential',
'Механизированная уборка ягод':'Mechanised berry harvesting','Новая ягодная плантация':'New berry plantation'
}

CZ={
'Механизированная уборка ягод — AGRO TAG':'Mechanizovaná sklizeň bobulovin — AGRO TAG',
'AGRO TAG: механизированная бесконтактная уборка ягод, оценка плантации, подбор конфигурации, запуск, обучение и сервис.':'AGRO TAG: bezkontaktní mechanizovaná sklizeň bobulovin, posouzení plantáže, výběr konfigurace, uvedení do provozu, školení a servis.',
'← Назад к AGRO TAG':'← Zpět na AGRO TAG',
'Эффективность':'Efektivita','Технология':'Technologie','Бережный принцип':'Šetrný princip','Модели':'Modely','Подготовка плантации':'Příprava plantáže','Система внедрения':'Systém zavedení','Консультация':'Konzultace','Преимущества':'Výhody','Для каких хозяйств':'Pro jaké farmy','Запросить консультацию':'Požádat o konzultaci',
'Инновационная технология':'Inovativní technologie','Воздушно-импульсная уборка':'Sklizeň pomocí vzduchových impulzů','Механизированная уборка ягод для свежего рынка':'Mechanizovaná sklizeň bobulovin pro čerstvý trh','Бесконтактная технология сбора спелой ягоды и фруктов управляемыми импульсами воздуха. Снижение зависимости от сезонных рабочих — при бережном воздействии на растение и урожай.':'Bezkontaktní technologie sklizně zralých bobulovin a ovoce pomocí řízených vzduchových impulzů. Snižuje závislost na sezónních pracovnících a zároveň šetrně působí na rostliny i úrodu.','Бесконтактная технология сбора спелой ягоды управляемыми импульсами воздуха. Снижение зависимости от сезонных рабочих — при бережном воздействии на растение и урожай.':'Bezkontaktní technologie sklizně zralých bobulovin pomocí řízených vzduchových impulzů. Snižuje závislost na sezónních pracovnících a zároveň šetrně působí na rostliny i úrodu.','Подобрать решение для хозяйства':'Vybrat řešení pro farmu','Как работает технология':'Jak technologie funguje',
'Типичные проблемы ручной уборки':'Typické problémy ruční sklizně','Когда ручной сбор становится ограничением':'Když se ruční sklizeň stává omezením','Ручной сбор ограничивает скорость, масштаб хозяйства и стабильность качества ягоды.':'Ruční sklizeň omezuje rychlost, velikost farmy a stabilitu kvality bobulovin.','Операционные ограничения':'Provozní omezení','Люди · сроки · масштаб':'Lidé · termíny · rozsah','Риски для качества урожая':'Rizika pro kvalitu úrody','Ягода · зрелость · хранение':'Plody · zralost · skladování','Дефицит сезонных рабочих':'Nedostatek sezónních pracovníků','Рост стоимости ручного труда':'Růst nákladů na ruční práci','Непредсказуемые сроки уборки':'Nepředvídatelné termíny sklizně','Ограничение масштаба хозяйства':'Omezení rozsahu farmy','Повреждение ягод':'Poškození plodů','Потеря защитного воскового налёта':'Ztráta ochranného voskového povlaku','Неоднородная зрелость партии':'Nestejnoměrná zralost šarže','Перегрев и задержка охлаждения':'Přehřátí a opožděné chlazení',
'Проблема':'Problém','Когда урожай есть, а рабочих не хватает':'Když je úroda připravena, ale chybějí pracovníci','Ручная уборка ягод требует большого количества сезонного персонала именно в короткий период, когда урожай необходимо собрать быстро и с минимальными потерями.':'Ruční sklizeň bobulovin vyžaduje velké množství sezónních pracovníků právě v krátkém období, kdy je nutné úrodu sklidit rychle a s minimálními ztrátami.','Снижение зависимости от сезонных рабочих':'Nižší závislost na sezónních pracovnících','Более предсказуемые сроки уборки':'Předvídatelnější termíny sklizně','Возможность обслуживать большие площади':'Možnost obsloužit větší plochy','Снижение операционных рисков':'Snížení provozních rizik','Ягодная плантация':'Plantáž bobulovin',
'Мы создаем новую экономику уборки':'Vytváříme novou ekonomiku sklizně','Мы создаём новую экономику уборки':'Vytváříme novou ekonomiku sklizně','Производительность, которая меняет экономику':'Produktivita, která mění ekonomiku','Экономика уборки':'Ekonomika sklizně','до 500+ кг/час':'až 500+ kg/h','500+ кг/час':'500+ kg/h','Ориентир в зависимости от модели, культуры и условий.':'Orientační výkon podle modelu, plodiny a podmínek.','до 4 га/день':'až 4 ha/den','Для ягодных плантаций в подходящих условиях.':'Pro plantáže bobulovin ve vhodných podmínkách.','Для голубичных плантаций в подходящих условиях.':'Pro borůvkové plantáže ve vhodných podmínkách.','Эквивалент сборщиков в сравнении со средней производительностью ручного труда.':'Ekvivalent počtu sběračů ve srovnání s průměrnou produktivitou ruční práce.',
'Сила природы — под контролем':'Síla přírody pod kontrolou','Регулируемые импульсы воздуха отделяют зрелую ягоду без непосредственного жёсткого механического контакта с растением.':'Řízené vzduchové impulzy oddělují zralé plody bez tvrdého přímého mechanického kontaktu s rostlinou.','Импульсные воздушные потоки':'Pulzní proudění vzduchu','Управляемая скорость и частота воздушного воздействия.':'Řízená rychlost a frekvence vzduchových impulzů.','Мягкая система приёма':'Šetrný sběrný systém','Эластичные элементы поглощают энергию падающей ягоды и снижают риск повреждения.':'Pružné prvky absorbují energii padajících plodů a snižují riziko poškození.','Дисковая система улавливания':'Diskový zachytávací systém','Минимизирует пространство вокруг ствола и помогает уменьшать потери ягоды.':'Minimalizuje mezery kolem kmene a pomáhá snižovat ztráty plodů.','Направляющие элементы':'Vodicí prvky','Направляют ветви и помогают адаптировать процесс к различным культурам.':'Vedou větve a pomáhají přizpůsobit proces různým plodinám.',
'Бережный принцип':'Šetrný princip','Механизированная уборка без жёсткого контакта':'Mechanizovaná sklizeň bez tvrdého kontaktu','Созревшая ягода удерживается растением слабее, чем незрелая. Правильно настроенное воздушное воздействие использует это различие.':'Zralý plod drží na rostlině slaběji než nezralý. Správně nastavené vzduchové impulzy tento rozdíl využívají.','Спелая ягода → отделяется':'Zralý plod → oddělí se','Настройки подбираются под культуру, зрелость и состояние насаждений.':'Nastavení se volí podle plodiny, zralosti a stavu porostu.','Незрелая ягода → остаётся':'Nezralý plod → zůstává','Цель — сохранить незрелые плоды на растении и снизить нежелательное воздействие.':'Cílem je ponechat nezralé plody na rostlině a omezit nežádoucí zásahy.',
'Культуры':'Plodiny','Одна технология — несколько ягодных культур':'Jedna technologie — několik druhů bobulovin','Основное современное применение — механизированная уборка голубики для свежего рынка. Технология также применяется для других ягодных культур.':'Hlavním současným využitím je mechanizovaná sklizeň borůvek pro čerstvý trh. Technologie se používá také u dalších druhů bobulovin.','Голубика':'Borůvky','Малина':'Maliny','Ежевика':'Ostružiny','Чёрная смородина':'Černý rybíz','Смородина':'Rybíz','Жимолость':'Zimolez',
'Механизированная уборка начинается с плантации':'Mechanizovaná sklizeň začíná u plantáže','Результат зависит не только от оборудования. Сорт, форма растения, схема посадки и состояние плантации напрямую влияют на эффективность уборки.':'Výsledek nezávisí jen na stroji. Odrůda, tvar rostlin, schéma výsadby a stav plantáže přímo ovlivňují efektivitu sklizně.','СОРТ':'ODRŮDA','Созревание и свойства ягоды':'Zrání a vlastnosti plodů','Равномерность созревания, размер, урожайность, вертикальная структура и плотность плода.':'Rovnoměrnost zrání, velikost, výnos, vertikální struktura a pevnost plodu.','ФОРМИРОВАНИЕ':'TVAROVÁNÍ','Архитектура куста':'Architektura keře','Узкое основание, высота нижних ветвей, плодоносящие побеги и объём зелёной массы.':'Úzká základna, výška spodních větví, plodonosné výhony a objem zelené hmoty.','ПОСАДКА':'VÝSADBA','Геометрия и условия':'Geometrie a podmínky','Междурядья, разворот техники, шпалеры, тоннели, температура, влажность и время уборки.':'Rozteč řádků, prostor pro otáčení techniky, konstrukce, tunely, teplota, vlhkost a termín sklizně.',
'Предварительная оценка':'Předběžné posouzení','Проверьте, подходит ли ваша плантация':'Ověřte vhodnost vaší plantáže','пространство для разворота техники':'prostor pro otáčení techniky','ориентир по высоте конструкций внутри ряда':'orientační výška konstrukcí v řádku','ориентир по высоте тоннелей':'orientační výška tunelů','пример междурядья в приведённой схеме':'příklad rozteče řádků ve schématu','Точные параметры определяются после оценки конкретной плантации и выбранной конфигурации оборудования.':'Přesné parametry se stanoví po posouzení konkrétní plantáže a zvolené konfigurace zařízení.',
'Конфигурации':'Konfigurace','Конфигурация под масштаб хозяйства':'Konfigurace podle velikosti farmy','Прицепная версия':'Tažená verze','Привод от ВОМ. Для хозяйств с подходящим трактором.':'Pohon přes vývodový hřídel. Pro farmy s vhodným traktorem.','Автономная прицепная версия':'Samostatně poháněná tažená verze','Собственный дизельный двигатель. Больше независимости от мощности тягача.':'Vlastní dieselový motor. Větší nezávislost na výkonu traktoru.','Самоходная версия':'Samojízdná verze','Для крупных хозяйств и интенсивной эксплуатации.':'Pro větší farmy a intenzivní provoz.','Посмотреть характеристики':'Zobrazit specifikace','Финальная комплектация и совместимость определяются после консультации.':'Konečná konfigurace a kompatibilita se stanoví po konzultaci.',
'Переход к механизации':'Přechod k mechanizaci','Механизация — это процесс, а не покупка одной машины':'Mechanizace je proces, ne jen nákup jednoho stroje','Существующая плантация':'Stávající plantáž','Год 1 · адаптация':'Rok 1 · adaptace','Год 2 · рост доли':'Rok 2 · růst podílu','Год 3 · масштабирование':'Rok 3 · rozšíření','Для неподготовленных плантаций переход может идти поэтапно: ориентировочно 10–15% → около 40% → 60%+ механизированной уборки.':'U nepřipravených plantáží může přechod probíhat postupně: přibližně 10–15 % → kolem 40 % → 60 %+ mechanizované sklizně.','Новая плантация':'Nová plantáž','Проектирование сразу под механизацию':'Návrh od začátku pro mechanizaci','При проектировании посадок под технологию возможно существенно быстрее наращивать долю механизированной уборки.':'Při navrhování nové výsadby pro tuto technologii lze podíl mechanizované sklizně zvyšovat výrazně rychleji.',
'Не просто оборудование. Система внедрения.':'Nejen zařízení. Systém zavedení.','Поставщик сопровождает внедрение технологии от первичной оценки хозяйства до запуска оборудования и последующей сервисной поддержки.':'Dodavatel provází zavedení technologie od prvotního posouzení farmy přes uvedení zařízení do provozu až po následný servis.','AGRO TAG сопровождает внедрение технологии от первичной оценки хозяйства до запуска оборудования и последующей сервисной поддержки.':'AGRO TAG provází zavedení technologie od prvotního posouzení farmy přes uvedení zařízení do provozu až po následný servis.','Анализ хозяйства':'Analýza farmy','Подбор технологии':'Výběr technologie','Оценка участка':'Posouzení lokality','Оценка плантации':'Posouzení plantáže','Поставка':'Dodávka','Запуск':'Uvedení do provozu','Обучение':'Školení','Сервис':'Servis','Запасные части':'Náhradní díly',
'Когда стоит рассматривать механизированную уборку':'Kdy uvažovat o mechanizované sklizni','Растущие затраты на сезонных рабочих':'Rostoucí náklady na sezónní pracovníky','Нехватка персонала':'Nedostatek pracovníků','Увеличение площади плантаций':'Rozšiřování plochy plantáží','Необходимость быстрее завершать уборку':'Potřeba dokončit sklizeň rychleji','Ориентация на свежий рынок':'Zaměření na čerstvý trh','Планирование новых посадок':'Plánování nových výsadeb','Возможность адаптации насаждений':'Možnost přizpůsobit porost','Потребность в предсказуемой производительности':'Potřeba předvídatelné produktivity',
'Международный опыт':'Mezinárodní zkušenosti','Технология работает на международных рынках':'Technologie funguje na mezinárodních trzích','машин в международной эксплуатации':'strojů v mezinárodním provozu','20+ лет':'20+ let','разработки и полевого опыта':'vývoje a zkušeností z provozu','машин в США за первые два года развития рынка':'strojů v USA během prvních dvou let rozvoje trhu',
'Новые проекты':'Nové projekty','Планируете новую ягодную плантацию?':'Plánujete novou plantáž bobulovin?','Лучший момент для подготовки к механизированной уборке — ещё до посадки. Мы можем обсудить геометрию рядов, технологический сценарий и требования к будущей механизации.':'Nejlepší čas na přípravu mechanizované sklizně je ještě před výsadbou. Můžeme probrat geometrii řádků, technologický scénář a požadavky na budoucí mechanizaci.','Обсудить проект плантации':'Probrat projekt plantáže',
'Подходит ли механизированная уборка вашему хозяйству?':'Je mechanizovaná sklizeň vhodná pro vaši farmu?','Расскажите о культуре, площади и существующей схеме посадки. AGRO TAG поможет предварительно оценить возможность механизации и подобрать конфигурацию оборудования.':'Popište plodinu, plochu a současné schéma výsadby. AGRO TAG pomůže předběžně posoudit možnost mechanizace a vybrat vhodnou konfiguraci zařízení.','Имя':'Jméno','Компания':'Společnost','Страна':'Země','Культура':'Plodina','Площадь, га':'Plocha, ha','Тип проекта':'Typ projektu','Телефон':'Telefon','Комментарий':'Komentář','Расширение существующей':'Rozšíření stávající plantáže','Оценить возможность механизации':'Posoudit možnost mechanizace','Механизированная уборка ягод':'Mechanizovaná sklizeň bobulovin','Новая ягодная плантация':'Nová plantáž bobulovin'
}

def apply(text,mapping):
    for k in sorted(mapping,key=len,reverse=True):
        text=text.replace(k,mapping[k])
    return text

base=src.read_text(encoding='utf-8')
for lang,mapping in [('en',EN),('cz',CZ)]:
    out=apply(base,mapping)
    out=re.sub(r'<html\s+lang="ru"',f'<html lang="{"en" if lang=="en" else "cs"}"',out,count=1)
    out=out.replace('src="assets/','src="../assets/').replace("src='assets/","src='../assets/")
    out=out.replace('src="/assets/','src="../assets/').replace("src='/assets/","src='../assets/")
    out=out.replace('src="/berry-harvesting-web.mp4"','src="../berry-harvesting-web.mp4"')
    out=out.replace('href="assets/','href="../assets/')
    # Local AGRO TAG link stays inside the language folder.
    nav=(
        '<nav class="langs">'
        + ('<a class="active" href="berry-harvesting.html">EN</a>' if lang=='en' else '<a href="../en/berry-harvesting.html">EN</a>')
        + ('<a href="../cz/berry-harvesting.html">CZ</a>' if lang=='en' else '<a class="active" href="berry-harvesting.html">CZ</a>')
        + '<a href="../berry-harvesting.html">RU</a></nav>'
    )
    out=re.sub(r'<nav class="langs">.*?</nav>',nav,out,count=1,flags=re.S)
    folder=ROOT/lang; folder.mkdir(parents=True,exist_ok=True)
    (folder/'berry-harvesting.html').write_text(out,encoding='utf-8')

print('Generated final EN/CZ berry-harvesting pages')
